In [7]:
import pkparse, run_pkpdb
run_pkpdb.run("4x0p")

saving inputs to: ../../data/pkegnn_INS/inputs
accessing source directories working if files printed: ../../../src_data/pdbs/fixed/101m.gz ../../../src_data/pdbs/rcsb/101m.pdb.gz
zipping entire db 0.0035082062085469564 mins
Wrote ../../data/pkegnn_dataset.zip
data prep time: 0.037054912249247236 mins 1 pdbs


In [8]:
pdb="4x0q"

In [9]:
!wget "https://files.rcsb.org/download/{pdb}.pdb.gz" -P ../../../src_data/pdbs/rcsb/

--2025-07-26 04:18:31--  https://files.rcsb.org/download/4x0q.pdb.gz
Resolving files.rcsb.org (files.rcsb.org)... 108.138.26.16, 108.138.26.123, 108.138.26.68, ...
Connecting to files.rcsb.org (files.rcsb.org)|108.138.26.16|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 493463 (482K) [application/octet-stream]
Saving to: ‘../../../src_data/pdbs/rcsb/4x0q.pdb.gz’

4x0q.pdb.gz         100%[===================>] 481.90K   754KB/s    in 0.6s    

2025-07-26 04:18:33 (754 KB/s) - ‘../../../src_data/pdbs/rcsb/4x0q.pdb.gz’ saved [493463/493463]



In [3]:
import numpy as np #after debug
dat=np.load("../../data/pkegnn_INS/inputs/101m.npz",allow_pickle=True)
z       = dat["z"]           # (N,)
pos     = dat["pos"]         # (N,3)
#seglen  = dat["seglen"]      # (S,)
anchor  = dat["sites"]      # (S,)
ids     = dat["ids"]         # (S,)
pks     = dat["pks"]         # (S,)
#oz      = dat["others"]
pks.dtype
print(z.shape,pos.shape,anchor.shape,ids.shape,pks.shape)#len(ids),len(pks))
print(z)
print(ids)
print(pos)
print(pks)
print(anchor)
np.load("/home/jrhoernschemeyer/Desktop/pkegnn/pKaSchNet/data/pkparse_OUTS/seqs/101m.npy")

(1275,) (1275, 3) (54, 3) (54,) (54,)
[7 6 6 ... 6 6 6]
[b'102A2' b'103A3' b'105A4' b'109A4' b'113A0' b'116A0' b'119A0' b'126A1'
 b'12A0' b'133A2' b'136A4' b'140A2' b'141A1' b'145A2' b'146A3' b'147A2'
 b'148A4' b'151A3' b'16A2' b'18A4' b'20A1' b'24A0' b'27A1' b'34A2' b'36A0'
 b'38A4' b'41A4' b'42A2' b'44A1' b'47A2' b'48A0' b'4A4' b'50A2' b'52A4'
 b'54A4' b'56A2' b'59A4' b'60A1' b'62A2' b'63A2' b'64A0' b'6A4' b'77A2'
 b'78A2' b'79A2' b'81A0' b'82A0' b'83A4' b'85A4' b'87A2' b'93A0' b'96A2'
 b'97A0' b'98A2']
[[23.025  4.49   8.222]
 [22.502  5.598  9.034]
 [23.627  6.382  9.736]
 ...
 [38.602  5.446 13.328]
 [39.713  5.441 12.363]
 [40.675  4.358 12.79 ]]
[ 0.6208    1.0709   -0.52919  -1.33583  -0.79473  -0.01653  -1.88213
 -0.15742  -0.28685   0.953    -0.42867  -0.48526  -3.072195  0.644
  4.0229    0.1457   -0.43961   1.8032    0.0309   -1.43619  -1.51218
 -4.38918  -1.04915   0.4658    0.71838  -0.98487   0.01458   1.4972
 -1.152     0.9767   -1.25469  -1.94096   0.3414   -1.78042  -

array(['MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRVKHLKTEAEMKASEDLKKHGVTVLTALGAILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSRHPGNFGADAQGAMNKALELFRKDIAAKYKELGYQG'],
      dtype='<U154')